#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a TexEd desktop='^9' state=floating follow=on

# AutoStart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
urxvtc &
lxpolkit &
nitrogen --restore &
dunst &
sh $HOME/.config/polybar/launch.sh &
orca &